//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3BHIF_PRE_2Semester_VILIMEK_BREUNIG.modell
{
    using System;
    using System.Collections.Generic;
    
    public partial class TundBvonP
    {
        public int Id { get; set; }
        public int Patient { get; set; }
        public System.DateTime Termin { get; set; }
        public string Behandlung { get; set; }
    
        public virtual Behandlung Behandlung1 { get; set; }
        public virtual Patient Patient1 { get; set; }
        public virtual Termin Termin1 { get; set; }
    }
}
